const LOADING_STARTED = "LOADING_STARTED";
const LOADING_DONE = "LOADING_DONE";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const USER_AUTHENTICATED = "USER_AUTHENTICATED";
const REGISTER_FAIL = "REGISTER_FAIL";
const USER_AUTHENTICATION_FAILED = "USER_AUTHENTICATION_FAILED";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT_USER = "LOGOUT_USER";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";

export {
    LOADING_DONE,
    LOADING_STARTED,
    REGISTER_SUCCESS,
    LOGIN_FAIL,
    LOGIN_SUCCESS,
    LOGOUT_USER,
    USER_AUTHENTICATED,
    USER_AUTHENTICATION_FAILED,
    REGISTER_FAIL,
    SET_ALERT,
    REMOVE_ALERT
}